---
title: "Clases de R"
author: "Eisen Carlos Usquiza Cruz"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#diseños experimentales ##DCA Dosis de fertilizacion nitrogenada: -0 -50 -100 -150 Rep:5

```{r}
library(agricolae)
dosis <- c(0, 50, 100, 150)
rep <- 5
dca <- design.crd(trt = dosis, r = rep, seed = 123)
print(dca$book)
library(ggplot2)
dca_df <- as.data.frame(dca$book)

```

##DBCA Factorial variedades de papa: canchan y peruanita

```{r}
trt <- c(4, 2)
outdesign <- design.ab(trt, r = 5, serie = 2)
book <- outdesign$book
book
library(ggplot2)
book_df <- as.data.frame(book)
colnames(book_df) <- c("Parcela", "Bloque", "Dosis", "Variedad")
ggplot(book_df, aes(x = as.factor(Bloque), y = interaction(Dosis, Variedad))) +
  geom_point() +
  labs(x = "Bloques", y = "Tratamientos (Dosis x Variedad)", title = "Diseño Factorial en Bloques Aleatorizados (4x2 con 5 Bloques)") +
  theme_minimal()
```

Base de datos \## Importar datos

```{r}
library(readxl)
fb <- read_excel("fb.xlsx", sheet = "fb")
str(fb)

```

## Modelo estadistico

```{r}
modelo <- aov(formula = lfa~riego+geno+geno+riego*geno+bloque, data=fb)
plot(modelo)
anova(modelo)

```

##Comparacion de medias

```{r}
mc <- agricolae::duncan.test(y= modelo,trt=c("riego","geno"))
mc
plot(mc)
```
